### PR TITLE
Change homepage to use large banner with large CTA

### PR DESCRIPTION
**Pull request by funrollloops**
It looks like this:

new homepage

### CODE REVIEW

**Comment by funrollloops** [comment]
I don't love the background image. There are probably better options.

**Comment by audiodude** [comment]
I feel like the words are going across the guy in the middle's creepy blurred out face, and it looks like an [Adbusters](https://www.adbusters.org/) mockup. It's very disturbing in my opinion.

**Comment by funrollloops** [comment]
Sigh, yeah. Should I look for another image, or drop the background entirely?

**Comment by audiodude** [comment]
I feel like it is important for the homepage to have a picture of some combination of
1. people
2. kids
3. hacks

Not necessarily in that order. I feel like it gives the org a soul.

**Comment by chriscook8** [comment]
HUmm.. kids,people,hacks.... kind of like the pictures already on the front page. So the goal is to make the CTA more prominent and 'above the fold'. What are our main CTA? Find a local group (locations, maybe with added geo search), Start a new group, and Donate?

**Comment by funrollloops** [comment]
Yeah, the image sucks. It has kids at the bottom, but they're not visible
with the banner auto sized like it is now. I like the pictures on the
homepage now, but they were too low resolution to use for a banner of this
size (or they were before all the blurring). Got any higher res versions?

I think the homepage should present two primary calls to action: join and
donate. If someone can't find a group near them, that should be our cue to
suggest they start one.

**Comment by funrollloops** [comment]
OK, here's the new version, without trying to copy the zero-four template too much:

hs-with-cta

**Comment by audiodude** [comment]
This version LGTM.

**Comment by funrollloops** [comment]
Chris, look ok to you?

**Comment by chriscook8** [comment]
Yeah It puts a big button above the fold... now we just have to do something with the info we collect from the form. Go ahead and pull it.. or I'll do it next time I'm messing with stuff

**Comment by chriscook8** [comment]
seeing it live, I think there's some stylesheet tweeks needed for the margin under the double lines

**Comment by audiodude** [comment]
I've added some extra margin below the double lines in #18. PTAL

**Pull request merged**
